steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/uuidpreloaddemo', '.']
# Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/uuidpreloaddemo']
# Deploy image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'uuidpreloaddemo', '--image', 'gcr.io/$PROJECT_ID/uuidpreloaddemo', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated',   
  "--set-env-vars","DATASET_ID=uuidpreloaddemo,APACHE_LOG_DIR=/var/log",
  '--max-instances','20','--concurrency','40']
images:
- gcr.io/$PROJECT_ID/uuidpreloaddemo
timeout: 1800s